# Generated by Django 6.1.1 on 2026-09-17 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('REGISTER', 'User Registered'), ('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'User Logged Out'), ('FILE_UPLOAD', 'File Uploaded'), ('FILE_VIEW', 'File Viewed'), ('FILE_DOWNLOAD', 'File Downloaded'), ('FILE_SHARE', 'File Shared'), ('FILE_ACCESS_DENIED', 'File Access Denied'), ('FILE_DELETE', 'File Deleted'), ('ROLE_CHANGED', 'User Role Changed'), ('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('SHARE_REVOKED', 'File Share Revoked')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied')], db_index=True, default='SUCCESS', max_length=20)),
                ('file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx')],
            },
        ),
    ]
